// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_Watson.Models;

#nullable disable

namespace Mission06_Watson.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20250213005729_seeds2")]
    partial class seeds2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Mission06_Watson.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Sci-Fi",
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "John",
                            Notes = "Mind-bending thriller",
                            Rating = "PG-13",
                            Title = "Inception",
                            Year = "2010"
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Sci-Fi",
                            Director = "The Wachowskis",
                            Edited = true,
                            LentTo = "Sarah",
                            Notes = "Classic cyberpunk",
                            Rating = "R",
                            Title = "The Matrix",
                            Year = "1999"
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Sci-Fi",
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "Michael",
                            Notes = "Epic space journey",
                            Rating = "PG-13",
                            Title = "Interstellar",
                            Year = "2014"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
